// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {converter} from '../models';

export function Convert(arg1:converter.ConvertRequest):Promise<converter.ConvertResponse>;

export function GetFileBase64(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenDirectory(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;
